### PR TITLE
no need to link libdri2

### PR DESCRIPTION
**Pull request by Red54**
Many distributions like Archlinux, Debian and Fedora do not have libdri2 in their repositories.

### CODE REVIEW

**Comment by Red54** [comment]
It seems that xorg-server provides DRI2SwapBuffers:

[root@Red54 ~]# find /usr/include/ -type f -exec grep -i --color DRI2SwapBuffers {} +
/usr/include/xorg/dri2.h:extern _X_EXPORT int DRI2SwapBuffers(ClientPtr client, DrawablePtr pDrawable,
/usr/include/X11/extensions/dri2proto.h:#define X_DRI2SwapBuffers 8
/usr/include/X11/extensions/dri2proto.h:} xDRI2SwapBuffersReq;
/usr/include/X11/extensions/dri2proto.h:#define sz_xDRI2SwapBuffersReq 32
/usr/include/X11/extensions/dri2proto.h:} xDRI2SwapBuffersReply;
/usr/include/X11/extensions/dri2proto.h:#define sz_xDRI2SwapBuffersReply 32
[root@Red54 ~]# 
[root@Red54 ~]# find /usr/lib/ -type f -exec grep -i --color DRI2SwapBuffers {} +
Binary file /usr/lib/xorg/modules/extensions/libglx.xorg matches
Binary file /usr/lib/libGL.so.1.2.0 matches
[root@Red54 ~]# 
[root@Red54 ~]# pacman -Qo /usr/include/xorg/dri2.h
/usr/include/xorg/dri2.h is owned by xorg-server-devel 1.13.2-1
[root@Red54 ~]# 
[root@Red54 ~]# pacman -Qo /usr/include/X11/extensions/dri2proto.h
/usr/include/X11/extensions/dri2proto.h is owned by dri2proto 2.8-1
[root@Red54 ~]# 
[root@Red54 ~]# pacman -Qo /usr/lib/xorg/modules/extensions/libglx.xorg
/usr/lib/xorg/modules/extensions/libglx.xorg is owned by xorg-server 1.13.2-1
[root@Red54 ~]# 
[root@Red54 ~]# pacman -Qo /usr/lib/libGL.so.1.2.0
/usr/lib/libGL.so.1.2.0 is owned by libgl 9.0.2-1
[root@Red54 ~]#

**Comment by Red54** [comment]
Screenshot - Sunday February 03 2013 - 07:10:23 HKT

**Comment by Red54** [comment]
You can also check the libUMP.so in https://github.com/linux-sunxi/mali-libs

[root@Red54 git]# git clone https://github.com/linux-sunxi/mali-libs
Cloning into 'mali-libs'...
remote: Counting objects: 143, done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 143 (delta 24), reused 143 (delta 24)
Receiving objects: 100% (143/143), 5.17 MiB | 458 KiB/s, done.
Resolving deltas: 100% (24/24), done.
[root@Red54 git]#
[root@Red54 git]# find . -type f -exec grep -i --color dri2 {} +
Binary file ./mali-libs/lib/r3p0/armhf/x11/libMali.so matches
Binary file ./mali-libs/lib/r2p4/armhf/x11/libEGL.so.1.4 matches
Binary file ./mali-libs/lib/r3p1/armhf/x11/libMali.so matches
[root@Red54 git]#
[root@Red54 git]# find .|grep -i --color ump
./mali-libs/lib/r3p0/armhf/framebuffer/libUMP.so
./mali-libs/lib/r3p0/armhf/x11/libUMP.so
./mali-libs/lib/r3p0/armel/android/libUMP.so
./mali-libs/lib/r2p4/armhf/x11/libUMP.so
./mali-libs/lib/r2p4/armel/framebuffer/libUMP.so
./mali-libs/lib/r3p1/armhf/framebuffer/libUMP.so
./mali-libs/lib/r3p1/armhf/x11/libUMP.so
[root@Red54 git]#

As you can see, no libUMP.so contains _dri2_, so there is no need to link libdri2.

Screenshot - Sunday February 03 2013 - 08:48:41 HKT

**Comment by rzk** [comment]
Hi again.

We link against libdri2 because the r3p0 version of libMali.so doesnt have the DRI2SwapBuffers. It has various DRI2 stuff (as you found using the find command), but not the swap buffers function. This was checked many times by many users, this repo was built not only by me alone.

We dont use the r2p4 or r3p1 that have DRI2SwapBuffers built in, these are there for advanced users who can upgrade/downgrade kernelspace drivers for themselves, our baseline is r3p0 version (both ARM hardfloat and Android libraries available - best out of other versions).

Link is needed because on most popular rootfs that is used (Linaro), Xorg is still 1.11.x and it doesnt have DRI2SwapBuffers built in. If I will apply your pull request - it will break GLES on Linaro, users will have missing symbols.

Please, read the wiki and dont spam pull requests. If you use ArchLinux - you presumably advanced user and can edit one line if needed. 

Please, do not take the fact that I will close this pull request personaly or as a sign of disrespect for other distros, if you want - you can do the lsb_release check in Makefile and change linking list for each distro. Other idea is to check for Xorg version.

Best Regards, and if you want to have this discussed with other guys from linux-sunxi, come over to our mailing list and send your pull requests as patches (read http://linux-sunxi.org/Submitting_patches).

**Comment by techn** [comment]
Here is another discussion about this topic.
https://groups.google.com/forum/?hl=fi&fromgroups=#!searchin/linux-sunxi/libump/linux-sunxi/zauuIi_6Tg8/Us08jK2ufWsJ

**Pull request closed without merging**
